[2024-06-09T03:00:27.974+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T03:00:27.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:00:25.790664+00:00 [queued]>
[2024-06-09T03:00:27.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:00:25.790664+00:00 [queued]>
[2024-06-09T03:00:27.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T03:00:28.001+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_upload_data> on 2024-06-09 03:00:25.790664+00:00
[2024-06-09T03:00:28.014+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T03:00:28.015+0000] {standard_task_runner.py:63} INFO - Started process 514 to run task
[2024-06-09T03:00:28.016+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'download_upload_data', 'manual__2024-06-09T03:00:25.790664+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmp60_ke77a']
[2024-06-09T03:00:28.018+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask download_upload_data
[2024-06-09T03:00:28.042+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:00:25.790664+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T03:00:28.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group 2' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='download_upload_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T03:00:25.790664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T03:00:25.790664+00:00'
[2024-06-09T03:00:28.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T03:00:28.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T03:00:28.086+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: download_and_uploadToDVCBucket() missing 1 required positional argument: 'gcs_location'
[2024-06-09T03:00:28.091+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=download_upload_data, run_id=manual__2024-06-09T03:00:25.790664+00:00, execution_date=20240609T030025, start_date=20240609T030027, end_date=20240609T030028
[2024-06-09T03:00:28.098+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task download_upload_data (download_and_uploadToDVCBucket() missing 1 required positional argument: 'gcs_location'; 514)
[2024-06-09T03:00:28.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T03:00:28.130+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T03:00:28.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
