[2024-06-09T03:04:47.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T03:04:47.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:04:45.233189+00:00 [queued]>
[2024-06-09T03:04:47.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:04:45.233189+00:00 [queued]>
[2024-06-09T03:04:47.117+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T03:04:47.123+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_upload_data> on 2024-06-09 03:04:45.233189+00:00
[2024-06-09T03:04:47.131+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=588) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T03:04:47.132+0000] {standard_task_runner.py:63} INFO - Started process 598 to run task
[2024-06-09T03:04:47.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'download_upload_data', 'manual__2024-06-09T03:04:45.233189+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmp4uljanfi']
[2024-06-09T03:04:47.138+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask download_upload_data
[2024-06-09T03:04:47.171+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T03:04:45.233189+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T03:04:47.245+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group 2' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='download_upload_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T03:04:45.233189+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T03:04:45.233189+00:00'
[2024-06-09T03:04:47.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T03:04:47.259+0000] {finsight_pipeline_functions.py:20} INFO - Downloading data for NFLX from 2002-01-01 to 2022-12-31.
[2024-06-09T03:04:47.726+0000] {logging_mixin.py:188} WARNING - [*********************100%%**********************]  1 of 1 completed
[2024-06-09T03:04:47.752+0000] {finsight_pipeline_functions.py:30} ERROR - Failed to download or upload data: 'str' object has no attribute 'xcom_push'
[2024-06-09T03:04:47.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T03:04:47.753+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 25, in download_and_uploadToDVCBucket
    ti.xcom_push(key='stock_data', value=stock_data.to_dict())
    ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'xcom_push'
[2024-06-09T03:04:47.763+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=download_upload_data, run_id=manual__2024-06-09T03:04:45.233189+00:00, execution_date=20240609T030445, start_date=20240609T030447, end_date=20240609T030447
[2024-06-09T03:04:47.770+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task download_upload_data ('str' object has no attribute 'xcom_push'; 598)
[2024-06-09T03:04:47.795+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T03:04:47.812+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T03:04:47.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
